- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Download etcd
    get_url:
      url: https://github.com/etcd-io/etcd/releases/download/v3.4.0/etcd-v3.4.0-linux-amd64.tar.gz
      dest: /home/ubuntu/
  
  - name: Extract etcd
    unarchive:
      src: /home/ubuntu/etcd-v3.4.0-linux-amd64.tar.gz
      dest: /home/ubuntu/
      remote_src: yes
  
  - name: Move etcd* to bin
    copy: 
      src: "{{ item }}"
      dest: /usr/local/bin/
      mode: a+x
      remote_src: yes
    with_items:
      - etcd-v3.4.0-linux-amd64/etcd
      - etcd-v3.4.0-linux-amd64/etcdctl

  - name: Creates directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /etc/etcd
      - /var/lib/etcd 
  
  - name: Copy certs
    copy: 
      src: "{{ item }}"
      dest: /etc/etcd
      remote_src: yes
    with_items:
      - ca.pem 
      - kubernetes.pem
      - kubernetes-key.pem 
  
  - name: Get INTERNAL_IP and ETCD_NAME
    shell:
      cmd: "{{ item }}"
      warn: false
    with_items:
      - curl -s http://169.254.169.254/latest/user-data/ | tr "|" "\n" | grep "^name" | cut -d"=" -f2 > ETCD_NAME.txt
      - curl -s http://169.254.169.254/latest/meta-data/local-ipv4 > INTERNAL_IP.txt
      
  - name: Move etcd.sh to remote
    copy: 
      src: script/etcd.sh 
      dest: /home/ubuntu/
    
  - name: Create etcd service
    become: true
    shell: sh etcd.sh

  - name: Reload system deamon
    become: true
    systemd:
      daemon_reload: yes
  
  - name: Enable etcd service
    become: true
    service:
      name: etcd
      enabled: yes

  - name: Start etcd service
    become: true
    service:
      name: etcd
      state: started
    